name: Cancel Redundant Workflows

on:
  workflow_run:
    workflows:
      - Allure Report Workflow
    types:
      - completed

jobs:
  cancel:
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.pull_requests != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Redundant Workflow
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}